[package]
name = "csscascade"
version = "0.0.0"
edition = "2024"
authors = ["Grida <hello@grida.co>", "Universe <universe@grida.co>"]
description = "A modern, Rust-native CSS Cascade & Style Resolution Engine designed for building browser-like rendering pipelines"
license = "Apache-2.0"
repository = "https://github.com/gridaco/grida"
homepage = "https://grida.co"
documentation = "https://docs.rs/csscascade"
keywords = ["css", "stylesheet", "rendering", "html", "svg"]
categories = ["web-programming", "parser-implementations", "text-processing"]
readme = "README.md"
publish = true

[lib]
crate-type = ["rlib"]

[dependencies]
cssparser = "0.36.0"
html5ever = "0.36.1"
selectors = "0.33.0"
